from test_single import test_multiple_characters


characters = [
    "Noobini Pizzanini",
    "Lirili Larila",
    "Tim Cheese",
    "FluriFlura",
    "Talpa Di Fero",
    "Svinina Bombardino",
    "Pipi Kiwi",
    "Trippi Troppi",
    "Tung Tung Tung Sahur",
    "Gangster Footera",
    "Bandito Bobritto",
    "Boneca Ambalabu",
    "Cacto Hipopotamo",
    "Ta Ta Ta Ta Sahur",
    "Tric Trac Baraboom",
    "Cappuccino Assassino",
    "Brr Brr Patapim",
    "Trulimero Trulicina",
    "Bambini Crostini",
    "Bananita Dolphinita",
    "Perochello Lemonchello",
    "Brri Brri Bicus Dicus Bombicus",
    "Avocadini Guffo",
    "Salamino Penguino",
    "Burbaloni Loliloli",
    "Chimpazini Bananini",
    "Ballerina Cappuccina",
    "Chef Crabracadabra",
    "Lionel Cactuseli",
    "Glorbo Fruttodrillo",
    "Blueberrini Octopusini",
    "Strawberelli Flamingelli",
    "Pandaccini Bananini",
    "Frigo Camelo",
    "Orangutini Ananassini",
    "Rhino Toasterino",
    "Bombardiro Crocodilo",
    "Bombombini Gusini",
    "Cavallo Virtuso",
    "Gorillo Watermelondrillo",
    "Spioniro Golubiro",
    "Zibra Zubra Zibralini",
    "Tigrilini Watermelini",
    "Coco Elefanto",
    "Girafa Celestre",
    "Gattatino Nyanino",
    "Matteo",
    "Tralalero Tralala",
    "Los Crocodillitos",
    "Odin Din Din Dun",
    "Statutino Libertino",
    "Trenostruzzo Turbo 3000",
    "Espresso Signora",
    "Ballerino Lololo",
    "Piccione Macchina",
    "Trigoligre Frutonni",
    "Orcalero Orcala",
    "La Vacca Staturno Saturnita",
    "Chimpanzini Spiderini",
    "Los Tralaleritos",
    "Las Tralaleritas",
    "Las Vaquitas Saturnitas",
    "Graipuss Medussi",
    "Chicleteira Bicicleteira",
    "La Grande Combinasion",
    "Nuclearo Dinossauro",
    "Garama and Madundung",
    "Tortuginni Dragonfruitini",
    "Pot Hotspot"
]


test_multiple_characters(characters)